---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/rust/nscp_client"
    schedule:
      interval: "weekly"
    groups:
      client:
        patterns:
          - "*"
